/** One-line descriptions for Top 10 Career Matches (page 9). */
export const CAREER_DESCRIPTIONS: Record<string, string> = {
  "AI Engineer": "Designs and builds artificial intelligence systems that solve real-world problems using machine learning and data.",
  "AI Researcher": "Explores new algorithms and AI methods to advance how machines learn, reason, and interact.",
  "Actor": "Performs in film, theatre, or television to bring characters and stories to life for audiences.",
  "Advertising Specialist": "Creates campaigns and messaging that persuade audiences to notice, trust, and buy a brand.",
  "Aerospace Engineer": "Designs aircraft, spacecraft, and related systems for aviation and space exploration.",
  "Animator": "Creates moving visuals and motion graphics for films, games, ads, and digital media.",
  "Art Director": "Leads the visual style and creative direction of design projects across media and brands.",
  "Auditor": "Examines financial records and processes to verify accuracy, compliance, and risk controls.",
  "Author": "Writes books, articles, or long-form content that informs, entertains, or inspires readers.",
  "Automotive Engineer": "Designs and improves vehicles, engines, and automotive systems for performance and safety.",
  "Banking Manager": "Oversees branch or banking operations, client relationships, lending, and team performance.",
  "Banking Officer": "Handles day-to-day banking services, accounts, loans, and customer financial needs.",
  "Brand Promoter": "Represents and markets brands at events, campaigns, and channels to grow visibility and sales.",
  "Brand Strategist": "Defines how a brand is positioned, perceived, and communicated in the market.",
  "Business Analyst": "Turns business data and needs into clear insights, requirements, and recommendations.",
  "Business Development Manager": "Identifies growth opportunities, partnerships, and new revenue for a company.",
  "Business Manager": "Leads teams and daily operations to meet targets, manage resources, and deliver results.",
  "Business Strategist": "Studies markets and competition to define long-term direction and winning strategies.",
  "CEO": "Sets vision and leads the entire organization, making top-level decisions on growth and performance.",
  "Chartered Accountant": "Manages accounts, audits, taxation, and financial compliance for organizations.",
  "Child Development Specialist": "Supports children's learning, behaviour, and growth through structured programmes.",
  "Civil Engineer": "Plans and builds infrastructure such as roads, bridges, buildings, and water systems.",
  "Community Relations Manager": "Builds relationships between organizations and the communities they serve.",
  "Community Service Manager": "Coordinates programmes that deliver social support and services to communities.",
  "Compliance Officer": "Ensures an organization follows laws, regulations, and internal policies.",
  "Content Creator": "Produces videos, posts, and digital content that engages and grows an audience.",
  "Content Strategist": "Plans what content to create and publish to achieve brand and business goals.",
  "Corporate Coach": "Helps professionals and leaders improve performance, skills, and workplace effectiveness.",
  "Corporate Executive": "Holds senior leadership responsibility for strategy, performance, and major decisions.",
  "Corporate Lawyer": "Advises companies on legal matters, contracts, disputes, and regulatory compliance.",
  "Counselor": "Guides individuals through personal, academic, or emotional challenges with structured support.",
  "Creative Director": "Leads creative vision across campaigns, design, and brand storytelling.",
  "Customer Experience Manager": "Improves how customers interact with a brand across products and services.",
  "Cybersecurity Expert": "Protects systems, networks, and data from cyber threats and security breaches.",
  "Cybersecurity Specialist": "Implements security tools and practices to defend digital assets and information.",
  "Data Analyst": "Collects and interprets data to uncover patterns and support business decisions.",
  "Data Scientist": "Uses statistics, programming, and machine learning to extract insights from complex data.",
  "Dietitian": "Advises on nutrition and diet plans to improve health and manage medical conditions.",
  "Digital Product Designer": "Designs intuitive digital products and user experiences for apps and websites.",
  "Diplomat": "Represents a country in international relations, negotiations, and policy dialogue.",
  "Drone Operator": "Flies and manages drones for surveying, delivery, media, or technical operations.",
  "Economist": "Studies markets, economies, and policies to explain trends and forecast outcomes.",
  "Editor": "Reviews, refines, and prepares written content for publication and clarity.",
  "Entrepreneur": "Starts and grows ventures by turning ideas into products, teams, and businesses.",
  "Event Host": "Presents and energizes live events, shows, and programmes for audiences.",
  "Event Manager": "Plans and executes events from concept to logistics, budget, and on-site delivery.",
  "Event Planner": "Organizes weddings, corporate events, and functions with detailed coordination.",
  "Fashion Designer": "Creates clothing and fashion collections reflecting style, trends, and brand identity.",
  "Film Editor": "Assembles footage into a coherent film or video with pacing, story, and impact.",
  "Finance Director": "Leads financial planning, reporting, and strategy at the senior management level.",
  "Finance Manager": "Oversees budgeting, forecasting, and financial operations for a department or company.",
  "Financial Analyst": "Evaluates financial data to guide investment, budgeting, and business decisions.",
  "Game Artist": "Creates visual assets, characters, and environments for video games.",
  "Game Developer": "Builds interactive games through coding, design, and gameplay mechanics.",
  "Government Officer": "Administers public programmes, policy implementation, and government services.",
  "Graphic Designer": "Creates visual designs for branding, marketing, print, and digital media.",
  "HR Director": "Leads human resources strategy, culture, talent, and organizational development.",
  "HR Manager": "Manages hiring, employee relations, policies, and workforce development.",
  "HR Trainer": "Designs and delivers training that builds employee skills and workplace capability.",
  "Healthcare Administrator": "Runs hospital or clinic operations, staff, budgets, and patient services.",
  "Hospitality Manager": "Oversees hotels, restaurants, or venues to deliver strong guest experiences.",
  "Human Rights Advocate": "Works to protect dignity, justice, and equal rights through policy and action.",
  "Illustrator": "Creates drawings and visuals for books, media, products, and commercial projects.",
  "Industrial Technician": "Maintains, repairs, and operates industrial machinery and production equipment.",
  "Influencer": "Builds an audience online and partners with brands through content and promotion.",
  "Innovation Consultant": "Helps organizations invent, test, and adopt new products and ways of working.",
  "Interior Designer": "Plans interior spaces for function, aesthetics, and client needs.",
  "Investment Banker": "Advises on mergers, fundraising, and large financial transactions for corporations.",
  "Investment Strategist": "Develops investment approaches and portfolio strategies for long-term returns.",
  "Journalist": "Reports news and stories through research, interviews, and published articles.",
  "Leadership Coach": "Develops leaders' skills in communication, decision-making, and team management.",
  "Life Coach": "Helps clients set goals, overcome obstacles, and build confidence in personal growth.",
  "Logistics Manager": "Coordinates supply chains, shipping, inventory, and delivery operations.",
  "Machine Learning Engineer": "Builds models and pipelines that let systems learn from data automatically.",
  "Management Consultant": "Advises companies on strategy, operations, and solving complex business problems.",
  "Marketing Executive": "Executes marketing campaigns across channels to reach and convert customers.",
  "Marketing Manager": "Plans and leads marketing strategy, campaigns, and brand growth initiatives.",
  "Marketing Strategist": "Designs how brands attract, engage, and retain their target audience.",
  "Mathematician": "Uses advanced mathematics to solve theoretical and applied problems in science and industry.",
  "Mechanical Engineer": "Designs machines, mechanical systems, and manufacturing processes.",
  "Media Presenter": "Hosts broadcasts, shows, or programmes for television, radio, or digital platforms.",
  "NGO Director": "Leads a non-profit organization's mission, programmes, funding, and impact.",
  "NGO Leader": "Guides social-impact organizations toward community goals and sustainable change.",
  "NGO Program Manager": "Plans and runs development or social programmes for non-profit organizations.",
  "Nurse": "Provides patient care, treatment support, and health monitoring in clinical settings.",
  "Occupational Therapist": "Helps people regain daily living and work skills after injury or illness.",
  "Operations Director": "Leads company-wide operations, efficiency, and execution of business processes.",
  "Operations Manager": "Manages daily workflows, teams, and systems to keep operations running smoothly.",
  "Philosopher": "Studies fundamental questions about knowledge, ethics, mind, and society.",
  "Photographer": "Captures images for events, brands, journalism, or artistic expression.",
  "Physiotherapist": "Treats movement and pain issues through exercise, therapy, and rehabilitation.",
  "Pilot": "Operates aircraft safely while navigating routes, weather, and flight protocols.",
  "Policy Advisor": "Researches and recommends policies for governments, firms, or institutions.",
  "Policy Advocate": "Promotes policy change on social, economic, or environmental issues.",
  "Policy Analyst": "Evaluates policies and data to inform government or organizational decisions.",
  "Policy Strategist": "Shapes long-term policy direction based on research and stakeholder needs.",
  "Product Designer": "Designs physical or digital products balancing user needs, function, and aesthetics.",
  "Product Manager": "Owns a product's vision and roadmap, aligning users, business, and engineering.",
  "Professor": "Teaches and researches at a university while advancing knowledge in a field.",
  "Project Manager": "Plans, coordinates, and delivers projects on time, scope, and budget.",
  "Psychologist": "Studies behaviour and mental processes to support therapy, research, or assessment.",
  "Public Relations Manager": "Manages an organization's public image, media relations, and communications.",
  "Public Relations Specialist": "Crafts press releases, media outreach, and reputation-building messages.",
  "Public Speaker": "Delivers talks and presentations that inform, motivate, or persuade audiences.",
  "Real Estate Consultant": "Advises clients on buying, selling, and investing in property.",
  "Research Scientist": "Conducts experiments and studies to advance scientific knowledge.",
  "Retail Director": "Leads retail strategy, stores, merchandising, and sales performance.",
  "Risk Manager": "Identifies and mitigates financial, operational, and strategic risks.",
  "Robotics Engineer": "Designs robots and automated systems for industry, research, and innovation.",
  "Sales Manager": "Leads sales teams, targets, and strategies to drive revenue growth.",
  "School Counselor": "Supports students with academic planning, wellbeing, and career guidance.",
  "Screenwriter": "Writes scripts and stories for films, series, and visual productions.",
  "Social Entrepreneur": "Builds ventures that solve social problems while sustaining impact.",
  "Social Media Strategist": "Plans content and campaigns to grow brand presence on social platforms.",
  "Social Worker": "Helps individuals and families access support, resources, and social services.",
  "Software Architect": "Designs the high-level structure of software systems for scale and reliability.",
  "Software Developer": "Writes and maintains code to build applications, tools, and digital products.",
  "Sports Manager": "Manages athletes, teams, or sports programmes and commercial partnerships.",
  "Startup Founder": "Builds a company from an idea through product, team, funding, and growth.",
  "Stock Trader": "Buys and sells securities to profit from market movements and analysis.",
  "Strategy Director": "Defines corporate strategy and guides major long-term business decisions.",
  "Supply Chain Manager": "Oversees sourcing, production, inventory, and delivery across the supply chain.",
  "Systems Architect": "Designs integrated technology systems that meet business and technical needs.",
  "Systems Engineer": "Engineers complex systems by integrating hardware, software, and processes.",
  "Teacher": "Educates students in schools through lessons, assessment, and classroom leadership.",
  "Technical Consultant": "Advises clients on technical solutions, implementation, and best practices.",
  "Technology Entrepreneur": "Founders technology-driven businesses that turn innovation into products.",
  "Therapist": "Provides structured mental health support through counselling and therapeutic methods.",
  "Tourism Manager": "Develops travel experiences, destinations, and tourism business operations.",
  "Training Consultant": "Designs workplace training programmes that build skills and performance.",
  "Training Manager": "Leads employee learning programmes, workshops, and capability development.",
  "Travel Consultant": "Plans trips and travel itineraries tailored to client preferences and budgets.",
  "Venture Capital Analyst": "Researches startups and markets to recommend investments for venture funds.",
  "Venture Capitalist": "Invests in high-growth startups and guides founders toward scale.",
  "Writer": "Produces written work across fiction, non-fiction, journalism, or content formats.",
};

export function getCareerDescription(careerName: string): string {
  return CAREER_DESCRIPTIONS[careerName]
    ?? `A professional path focused on ${careerName.toLowerCase()} roles that align with your strengths and interests.`;
}
