export const PERSONALITY_DISPLAY_NAMES: Record<string, string> = {
  ISTJ: "The Systematic Organizer",
  ISFJ: "The Protective Supporter",
  INFJ: "The Purpose Driven Guide",
  INTJ: "The Master Strategist",
  ISTP: "The Practical Problem Solver",
  ISFP: "The Artist",
  INFP: "The Value Creator",
  INTP: "The Curious",
  ESTP: "The Action Taker",
  ESFP: "The Joyful Performer",
  ENFP: "The Visionary",
  ENTP: "The Entrepreneur",
  ESTJ: "The Strategic Leader",
  ESFJ: "The Community Builder",
  ENFJ: "The Mentor Leader",
  ENTJ: "The Visionary Director",
};

export const PERSONALITY_STREAMS: Record<string, string> = {
  ISTJ: "Commerce / Science",
  ISFJ: "Arts / Science",
  INFJ: "Arts / Humanities",
  INTJ: "Science / Commerce",
  ISTP: "Science",
  ISFP: "Arts / Humanities",
  INFP: "Arts / Humanities",
  INTP: "Science",
  ESTP: "Commerce / Science",
  ESFP: "Arts / Commerce",
  ENFP: "Arts / Commerce",
  ENTP: "Commerce / Science",
  ESTJ: "Commerce",
  ESFJ: "Arts / Commerce",
  ENFJ: "Arts / Humanities",
  ENTJ: "Commerce / Science",
};

export const PERSONALITY_SUBJECTS: Record<string, string[]> = {
  ISTJ: ["Mathematics", "Accountancy", "Economics", "Statistics"],
  ISFJ: ["Biology", "Psychology", "Sociology", "Education"],
  INFJ: ["Psychology", "Literature", "Philosophy", "Sociology"],
  INTJ: ["Mathematics", "Physics", "Computer Science", "Economics"],
  ISTP: ["Physics", "Mathematics", "Computer Science"],
  ISFP: ["Design", "Fine Arts", "Media Studies"],
  INFP: ["Literature", "Psychology", "Philosophy"],
  INTP: ["Mathematics", "Physics", "Computer Science", "Statistics"],
  ESTP: ["Business Studies", "Economics", "Mathematics"],
  ESFP: ["Media Studies", "Communication", "Performing Arts"],
  ENFP: ["Marketing", "Psychology", "Media Studies"],
  ENTP: ["Entrepreneurship", "Economics", "Computer Science"],
  ESTJ: ["Accountancy", "Business Studies", "Economics"],
  ESFJ: ["Psychology", "Sociology", "Communication"],
  ENFJ: ["Psychology", "Political Science", "Literature"],
  ENTJ: ["Economics", "Mathematics", "Business Studies"],
};

export const PERSONALITY_CAREERS: Record<string, string[]> = {
  ISTJ: ["Chartered Accountant", "Auditor", "Financial Analyst", "Banking Officer", "Data Analyst", "Civil Engineer", "Operations Manager", "Risk Manager", "Compliance Officer", "Government Officer"],
  ISFJ: ["Nurse", "Teacher", "Counselor", "Physiotherapist", "Social Worker", "Occupational Therapist", "Child Development Specialist", "Healthcare Administrator", "Dietitian", "Community Service Manager"],
  INFJ: ["Psychologist", "Counselor", "Author", "Policy Analyst", "Social Entrepreneur", "Human Rights Advocate", "Professor", "NGO Director", "Diplomat", "Life Coach"],
  INTJ: ["Data Scientist", "AI Engineer", "Software Architect", "Investment Strategist", "Research Scientist", "Economist", "Systems Engineer", "Policy Strategist", "Management Consultant", "Cybersecurity Expert"],
  ISTP: ["Mechanical Engineer", "Robotics Engineer", "Pilot", "Automotive Engineer", "Aerospace Engineer", "Drone Operator", "Industrial Technician", "Cybersecurity Specialist", "Systems Engineer", "Technical Consultant"],
  ISFP: ["Graphic Designer", "Fashion Designer", "Photographer", "Animator", "Interior Designer", "Illustrator", "Film Editor", "Art Director", "Product Designer", "Game Artist"],
  INFP: ["Writer", "Screenwriter", "Psychologist", "Creative Director", "Social Worker", "Journalist", "Editor", "Content Strategist", "Therapist", "NGO Program Manager"],
  INTP: ["Research Scientist", "AI Researcher", "Software Developer", "Mathematician", "Data Scientist", "Game Developer", "Philosopher", "Economist", "Systems Architect", "Machine Learning Engineer"],
  ESTP: ["Entrepreneur", "Stock Trader", "Sales Manager", "Business Development Manager", "Event Manager", "Sports Manager", "Operations Manager", "Real Estate Consultant", "Marketing Executive", "Logistics Manager"],
  ESFP: ["Actor", "Event Host", "Public Relations Specialist", "Hospitality Manager", "Influencer", "Travel Consultant", "Brand Promoter", "Media Presenter", "Content Creator", "Tourism Manager"],
  ENFP: ["Marketing Manager", "Brand Strategist", "Startup Founder", "Creative Director", "Journalist", "Advertising Specialist", "Public Speaker", "HR Trainer", "Content Creator", "Social Media Strategist"],
  ENTP: ["Startup Founder", "Product Manager", "Innovation Consultant", "Venture Capital Analyst", "Business Strategist", "Technology Entrepreneur", "Marketing Strategist", "Digital Product Designer", "Management Consultant", "Business Analyst"],
  ESTJ: ["Business Manager", "Corporate Executive", "Chartered Accountant", "Project Manager", "Banking Manager", "Operations Director", "Government Officer", "Supply Chain Manager", "Retail Director", "Finance Manager"],
  ESFJ: ["HR Manager", "Teacher", "Event Planner", "Hospitality Manager", "Community Relations Manager", "School Counselor", "Public Relations Manager", "Training Manager", "Social Worker", "Customer Experience Manager"],
  ENFJ: ["Teacher", "Leadership Coach", "HR Director", "NGO Leader", "Counselor", "Public Speaker", "Social Entrepreneur", "Policy Advocate", "Training Consultant", "Corporate Coach"],
  ENTJ: ["CEO", "Investment Banker", "Management Consultant", "Strategy Director", "Entrepreneur", "Venture Capitalist", "Corporate Lawyer", "Business Analyst", "Finance Director", "Policy Advisor"],
};
